### PR TITLE
[MOB-2848] Add support for Mexican release notes

### PR DESCRIPTION
**Pull request by d4r1091**
[MOB-2848]

## Context

We are doing some ASO (App Store Optimization) and that includes some language tests for release notes as well.
As part of this, we are adding the Mexican language to our release notes automation.

## Approach

- Transifex seem not to have the option to mirror another language so I ended up adding it and copying the translations from the Spanish one
- Included the new folder in our Fastlane's metadata 

## Other

Took the occasion to fix the release notes Github Workflow ([already tested](https://github.com/ecosia/ios-browser/actions/runs/10629341903) till the "upload to App Store Connect" step)

The merge of both this PR and the Transifex one https://github.com/ecosia/ios-browser/pull/766 will trigger the Job which will then fail (?) as there will be no chance to update the metadata for the given version. So will add the Don't Merge label to both.

[MOB-2848]: https://ecosia.atlassian.net/browse/MOB-2848?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by d4r1091** [comment]
Await the new version drafted (likely 10.1.1) before merging in those.

**Review by lucaschifino — APPROVED** [review]
🇲🇽 ✅

**Comment by lucaschifino** [comment]
> Await the new version drafted (likely 10.1.1) before merging this.

I've already added `10.1.1` to App Store Connect as this will be drafted very soon once bug fixes are merged. I guess we could merge this already then as we'll likely still use the generic release notes 🙂

**Comment by d4r1091** [comment]
If we merge this, the workflow to upload the release notes will be triggered as there are changes in the `fastlane/metadata` folder. The way the script works is to check the version from the `Common.xcconfig` and tell fastlane to push the release notes against that one. If the version hasn't been updated yet on the `Common.xcconfig` file, fastlane will try to update the released version.

**Comment by lucaschifino** [comment]
> If the version hasn't been updated yet on the `Common.xcconfig` file, fastlane will try to update the released version.

You're 💯 right, did not realise that 👍

**Comment by d4r1091** [comment]
Removing the `don't merge` label. It is mergeable now 👍

**Pull request merged**
