### PR TITLE
[MOB-1932] Remove Rebrand Intro

### PR DESCRIPTION
**Pull request by d4r1091**
[MOB-1932]

## Context

The brand refresh happened more than a year ago. It’s time to clean up the code that promotes the new design.

## Approach

- Assets and Source Code removal
- `// Ecosia` specific business logic to show the rebrand intro removal
- Hidden Settings for Rebrand Intro removal
- English Strings removal alongside their code references

### Checklist

- [x] I performed some relevant testing on a real device and/or simulator
- [x] I updated only the [english localization source files](Client/Ecosia/L10N/es.lproj) if needed
- [x] I am using the correct version from [core](https://github.com/ecosia/ios-core), including any necessary changes for this ticket and pointing to `main` instead of a feature branch

[MOB-1932]: https://ecosia.atlassian.net/browse/MOB-1932?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by lucaschifino — COMMENTED** [review]
Looking good 🧹 

Waiting for the core to be finalised for the final 👍

**Review by lucaschifino — DISMISSED** [review]
LGTM 🧹

**Comment by d4r1091** [comment]
Updated after solving conflicts.
Also, for some reason, the default GitHub button changed while (meant to) `Squash and Merge` the previous PR. Ended up with `Rebase and Merge`. Annoying but wanted to point it out in case it happens to anyone to experiences the same behaviour.

**Review by lucaschifino — APPROVED** [review]
🟢 🏁 

I think we can check if possible to not dismiss reviews if nothing changed (only merged with main)

**Comment by d4r1091** [comment]
Sure thing I'll have a look into it now that we've been working with this new mechanism for a while.
Nice reminder 👍

**Pull request merged**
