### PR TITLE
MOB-1877 Remove How Ecosia Works from Your Impact sections

### PR DESCRIPTION
**Pull request by lucaschifino**
[MOB-1877](https://ecosia.atlassian.net/browse/MOB-1877)

## Context
Given the Google Market changes, we need to remove the "How Ecosia Works" section from Your Impact page

## Approach
- Removed the `info` enum case from `YourImpact.Section.Explore`.
- Remove all instances of the used Strings. Have not pushed to transifex as I understood that should be done automatically now 🤖
- Remove the image used
- Remove the Analytics item

## Other
- Also took the opportunity to remove all `TopSite` analytics items as none of them were in use

### CODE REVIEW

**Review by d4r1091 — APPROVED** [review]
👋 😢 but neat work 👌 

Interesting that we didn't have any sort of test written on this list 😅 , at least DataSource wise 😝... noted for our future selves ✍️

**Comment by ecotopian** [comment]
> Remove all instances of the used Strings. Have not pushed to transifex as I understood that should be done automatically now 🤖

Is that so? @d4r1091 I thought the integration will only add PRs to `main` when translations have changed. Does the integration also monitor changes in the sources file and sync them with the transifex, i.e. adding and removing source translations?

**Review by ecotopian — APPROVED** [review]
Looks great! I just had one doubt regarding the transifex integration worfklow, but that's not code related.

**Comment by d4r1091** [comment]
Yes @ecotopian, as per what the Transifex doc says, it integration observes changes in the mentioned files in the config and triggers the sync appropriately.

**Pull request merged**
