### PR TITLE
[MOB-2847] Fix external link open after >4 hours of inactivity

### PR DESCRIPTION
**Pull request by lucaschifino**
[MOB-2847]

## Context

On some devices, opening an external link while the **app has been closed for more than 4 hours** fails and shows a blank NTP. Even so, a tab with the link is still opened under the hood.

### Debugging

We were not able to reproduce with attached debugger (even using the "Wait for the executable to be launched" option). Even so, it happens on AppCenter, so we were able to debug it via a version from this branch containing some temporary Analytics.

### Solution

We figured out there a a bug on the functionality to open homepage after 4 hours of inactivity. [This line of code](https://github.com/ecosia/ios-browser/blob/3ccf192e60739c43b03103b32d8ce2c782ce1026/Client/Frontend/Browser/StartAtHomeHelper.swift#L30) is meant to block this behaviour when opened from external link, but `openedFromExternalSource` was not properly set every time that happened.

I've updated how this works on the `SceneDelegate` so this is always set correctly. This was done using a fix already implemented on Firefox by https://github.com/mozilla-mobile/firefox-ios/pull/18792. The quote on the PR explains it well:

> Add openedFromExternalSource = true in most places where we open from external deep links. This openedFromExternalSource is used to ensure we don't start at home when a deep link was request by the user. The user should always have what they request to be opened, opened.

A video with the fix was uploaded on [this comment on the ticket](https://ecosia.atlassian.net/browse/MOB-2847?focusedCommentId=94608).

[MOB-2847]: https://ecosia.atlassian.net/browse/MOB-2847?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by d4r1091** [comment]
Acknowledged the changes 👍 . Double checking on why we need a PR? Is it for transparency and for us checking the changes in progress?

**Comment by lucaschifino** [comment]
> Acknowledged the changes 👍 . Double checking on why we need a PR? Is it for transparency and for us checking the changes in progress?

Just transparency since it's easier to check CI and see which attempts are being made / document them.

The idea is to also use it once we have a fix, reverting the previous changes.

**Comment by d4r1091** [comment]
Hey @lucaschifino 👋 , again really awesome findings!

Quick question on the changed code, are we planning to add some Ecosia's comments there? Conscious it's still with the "don't merge" label. Asked in advance.

**Comment by lucaschifino** [comment]
> Hey @lucaschifino 👋 , again really awesome findings!
> 
> Quick question on the changed code, are we planning to add some Ecosia's comments there? Conscious it's still with the "don't merge" label. Asked in advance.

@d4r1091 thanks for reaching out 🙌 This is actually supposed to be ready to merge, I forgot to remove the label, just did it now 🙏 

About the comments, I purposely left them out since this is something that Firefox already did on their code (PR linked on the description), so when we upgrade our base code again, we should grab what they have and not change these lines.

**Review by d4r1091 — APPROVED** [review]
Cool thanks for adding further context to it!

**Pull request merged**
