### PR TITLE
Version bump to 10.2.0

### PR DESCRIPTION
**Pull request by lucaschifino**
Triggers [release 10.2.0](https://ecosia.atlassian.net/projects/MOB/versions/10819/tab/release-report-all-issues)

### CODE REVIEW

**Review by d4r1091 — DISMISSED** [review]
🚀

**Comment by lucaschifino** [comment]
@d4r1091 I'm getting some weird tests behaviour and found a broken Snapshot one (since we removed the Bookmark Nudge from the NTP) - will ask for review again once that is sorted

**Review by d4r1091 — APPROVED** [review]
🚀

**Comment by lucaschifino** [comment]
Like discussed, will merge to not block the release and follow-up with tests later if needed 🙏

**Pull request merged**
