### PR TITLE
MOB-1852 Udpate macosx xcode ci

### PR DESCRIPTION
**Pull request by d4r1091**
[MOB-1852](https://ecosia.atlassian.net/browse/MOB-1852)

## Context

Currently, we use Xcode 14.2 to run our unit tests via GH Actions and our deploy pipelines in CircleCI. 

In order to benefit from internal API fixes, we shall upgrade to Xcode 14.3.1 as being the latest stable Xcode release.

## Approach

Updated both GH and CircleCI to use the latest 14.3.1 Xcode..
Two separate commits to it's easier to revert one of the CIs in case.

## Other

- Flag 🎏 : Github MacOS13 is still marked as beta - let's check it out though 😉

🚨Last commit to be reverted. Needed to trigger and hopefully pass tests only

### CODE REVIEW

**Review by lucaschifino — COMMENTED** [review]
I've noticed some tests are failing and as far as I can tell those seem to also happen locally using Xcode 14.3... I think we have discussed it before and I have not investigated the issue, just thought I would point it 🙂

**Comment by d4r1091** [comment]
To add further context, it is an issue that Firefox has spotted in similar scenarios.
Though our base version is different. I'll try to gather thoughts and keep you posted.

**Comment by ecotopian** [comment]
> To add further context, it is an issue that Firefox has spotted in similar scenarios.
> Though our base version is different. I'll try to gather thoughts and keep you posted.

Wondering if those failing tests really indicate a malfunction of the app with a higher base sdk, or if they are simply false negatives. If it's the latter we can simply deactivate them.

**Comment by d4r1091** [comment]
I seriously doubt that those tests indicate a clear malfunction based on the SDKs.
As part of this ticket, whilst investigating for the failing ones matching FF codebase, I fixed a crash happening on some tests. I would consider myself happy with deactivating the rest of the tests and monitor the FF Github issues. Happy to take care of that as background job.
If I'll get both your 👍 , I'll deactivate the tests, so far only beloging to `TabDisplayManagerTests`, wih no further crashes.

**Comment by ecotopian** [comment]
> I seriously doubt that those tests indicate a clear malfunction based on the SDKs.
> As part of this ticket, whilst investigating for the failing ones matching FF codebase, I fixed a crash happening on some tests. I would consider myself happy with deactivating the rest of the tests and monitor the FF Github issues. Happy to take care of that as background job.
> If I'll get both your 👍 , I'll deactivate the tests, so far only beloging to `TabDisplayManagerTests`, wih no further crashes.

Fine for me. Let's deactivate the `TabDisplayManagerTests` and remind ourselves to reactivate them after the next upgrade 🤓

**Comment by d4r1091** [comment]
Tackled changes @ecotopian @lucaschifino . Tagging for better reach prior to releasing

**Review by ecotopian — APPROVED** [review]
Looks good to me 🚀

**Review by lucaschifino — APPROVED** [review]
LGTM 🙌

**Comment by ecotopian** [comment]
> Tackled changes @ecotopian @lucaschifino . Tagging for better reach prior to releasing

@d4r1091 Are tests passing now? As they haven't run with the latest commit.

**Comment by d4r1091** [comment]
Yes they do @ecotopian 👍 - ref https://github.com/ecosia/ios-browser/actions/runs/5446548420
The last commit was used to revert the trigger

**Pull request merged**
