### PR TITLE
Add Beta debug scheme

### PR DESCRIPTION
**Pull request by ecotopian**
- Adding a new scheme called BetaDebug
- This will use our beta identifier `com.ecosia.ecosiaapp.firefox` for all configurations (run, test, archive etc) installing the beta in parallel to our prod app
- removed unused schemes to reduce noise in the scheme selector

Screenshot 2023-04-14 at 13 39 20

### CODE REVIEW

**Review by lucaschifino — COMMENTED** [review]
Looks good 🚀 Nice job with the cleanings as well 🧹

Just one comment: 
I noticed there are no `.xcscheme` files committed, doesn't a new scheme require those?
I checked the branch to try it out and could not see the schema listed in the project, but I do see the `BetaDebug` configuration in the Client target, am I missing something here? 😅

**Comment by ecotopian** [comment]
> Looks good 🚀 Nice job with the cleanings as well 🧹
> 
> Just one comment: I noticed there are no `.xcscheme` files committed, doesn't a new scheme require those? I checked the branch to try it out and could not see the schema listed in the project, but I do see the `BetaDebug` configuration in the Client target, am I missing something here? 😅

Indeed great find! I forgot to mark the new scheme as shared. Fixed now 💪

**Review by lucaschifino — APPROVED** [review]
Awesome, all good now 🙌

**Review by d4r1091 — APPROVED** [review]
Awesome stuff @ecotopian .
QQ, any particular need to keep `.firefox` ? What would have been the effort to make something like `.beta` ?

**Comment by ecotopian** [comment]
> Awesome stuff @ecotopian .
> QQ, any particular need to keep `.firefox` ? What would have been the effort to make something like `.beta` ?

@d4r1091 Indeed there is some hook that keeps from ironing out this naming flaw 🙄  We do have a testflight app with a public channel with that particular identifier. We use this occasionally to test critical new features like migrations and upgrades. Moving to a new identifier would mean loosing this user base 😢

**Pull request merged**
